# This file is auto-generated by scripts/update_banim_img_rules.py
# Do not edit manually.

# Img_0861AD94: 16x9 tiles (144 total)
graphics/banim/assets/img/0061AD94_Img_0861AD94.4bpp: graphics/banim/assets/img/0061AD94_Img_0861AD94.png
	$(GBAGFX) $< $@ -num_tiles 144

# Img_BarrierBg: 16x11 tiles (176 total)
graphics/banim/assets/img/0068D6D0_Img_BarrierBg.4bpp: graphics/banim/assets/img/0068D6D0_Img_BarrierBg.png
	$(GBAGFX) $< $@ -num_tiles 176

# Img_EfxLiveBG_B: 28x6 tiles (168 total)
graphics/banim/assets/img/00670548_Img_EfxLiveBG_B.4bpp: graphics/banim/assets/img/00670548_Img_EfxLiveBG_B.png
	$(GBAGFX) $< $@ -num_tiles 168

# Img_EfxLokmsunaObj: fixed 48 tiles
graphics/banim/assets/img/00758218_Img_EfxLokmsunaObj.4bpp: graphics/banim/assets/img/00758218_Img_EfxLokmsunaObj.png
	$(GBAGFX) $< $@ -num_tiles 48

# Img_ExcaliburBg1: 16x3 tiles (48 total)
graphics/banim/assets/img/0072E25C_Img_ExcaliburBg1.4bpp: graphics/banim/assets/img/0072E25C_Img_ExcaliburBg1.png
	$(GBAGFX) $< $@ -num_tiles 48

# Img_LunaBg3_B: 16x11 tiles (176 total)
graphics/banim/assets/img/0072B5BC_Img_LunaBg3_B.4bpp: graphics/banim/assets/img/0072B5BC_Img_LunaBg3_B.png
	$(GBAGFX) $< $@ -num_tiles 176

# Img_ShineBg1: 16x13 tiles (208 total)
graphics/banim/assets/img/00725DCC_Img_ShineBg1.4bpp: graphics/banim/assets/img/00725DCC_Img_ShineBg1.png
	$(GBAGFX) $< $@ -num_tiles 208

# Img_ShineBg2: 16x3 tiles (48 total)
graphics/banim/assets/img/0072796C_Img_ShineBg2.4bpp: graphics/banim/assets/img/0072796C_Img_ShineBg2.png
	$(GBAGFX) $< $@ -num_tiles 48

# Img_ThunderSpellBg: fixed 134 tiles
graphics/banim/assets/img/005F2DC0_Img_ThunderSpellBg.4bpp: graphics/banim/assets/img/005F2DC0_Img_ThunderSpellBg.png
	$(GBAGFX) $< $@ -num_tiles 134
