#!/usr/bin/env python3
"""Generate make rules that enforce width/num_tiles when rebuilding banim .4bpp files.

The rules are derived from ROM data so that PNG round-trips remain lossless.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path
from typing import Dict, Tuple

ROOT = Path(__file__).resolve().parents[1]
ROM_PATH = ROOT / "baserom.gba"
LABELS_CSV = ROOT / "reports" / "data_banim_incbin_labels.csv"
ASSET_MAP_CSV = ROOT / "reports" / "data_banim_asset_map.csv"
RULES_MK = ROOT / "graphics" / "banim" / "assets" / "img" / "banim_img_rules.mk"

# Constraints gathered from code analysis (widths) or ROM tile counts (num_tiles)
CONSTRAINTS = {
    "Img_ThunderSpellBg": {"num_tiles": 134},
    "Img_0861AD94": {"width": 16},
    "Img_EfxLiveBG_B": {"width": 28},
    "Img_BarrierBg": {"width": 16},
    "Img_ShineBg1": {"width": 16},
    "Img_ShineBg2": {"width": 16},
    "Img_LunaBg3_B": {"width": 16},
    "Img_ExcaliburBg1": {"width": 16},
    "Img_EfxLokmsunaObj": {"num_tiles": 48},
}


def read_label_offsets() -> Dict[str, Tuple[int, int]]:
    table = {}
    with LABELS_CSV.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            label = row["global"] or row["label"]
            if not label:
                continue
            start = eval(row["start"].replace(" ", ""), {"__builtins__": None}, {})
            size = eval(row["size"].replace(" ", ""), {"__builtins__": None}, {})
            table[label] = (start, size)
    return table


def build_label_to_path() -> Dict[str, Path]:
    mapping: Dict[str, Path] = {}
    with ASSET_MAP_CSV.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            new_path = Path(row["new_path"])
            if new_path.suffix != ".lz":
                continue
            stem = new_path.with_suffix("").stem
            if "_" not in stem:
                continue
            label = stem.split("_", 1)[1]
            if not label:
                continue
            mapping[label] = new_path.with_suffix("")
    return mapping


def lz77_decompress(data: bytes) -> bytes:
    if not data or data[0] != 0x10:
        return data
    size = data[1] | (data[2] << 8) | (data[3] << 16)
    src = 4
    out = bytearray()
    while len(out) < size:
        if src >= len(data):
            raise ValueError("LZ data truncated")
        flags = data[src]
        src += 1
        for _ in range(8):
            if flags & 0x80:
                b1 = data[src]
                b2 = data[src + 1]
                src += 2
                disp = ((b1 & 0x0F) << 8) | b2
                length = (b1 >> 4) + 3
                offset = disp + 1
                for _ in range(length):
                    out.append(out[-offset])
                    if len(out) >= size:
                        break
            else:
                out.append(data[src])
                src += 1
            flags = (flags << 1) & 0xFF
            if len(out) >= size:
                break
    return bytes(out)


def compute_tile_counts(label_offsets: Dict[str, Tuple[int, int]]) -> Dict[str, int]:
    rom = ROM_PATH.read_bytes()
    result = {}
    for label in CONSTRAINTS:
        start, size = label_offsets[label]
        chunk = rom[start : start + size]
        raw = lz77_decompress(chunk)
        result[label] = len(raw) // 32
    return result


def emit_rules(label_to_path: Dict[str, Path], tile_counts: Dict[str, int]) -> None:
    RULES_MK.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# This file is auto-generated by scripts/update_banim_img_rules.py",
        "# Do not edit manually.",
        "",
    ]
    for label in sorted(CONSTRAINTS.keys()):
        path_4bpp = label_to_path.get(label)
        if path_4bpp is None:
            raise KeyError(f"Missing asset path for {label}")
        png_path = path_4bpp.with_suffix(".png")
        tiles = tile_counts[label]
        spec = CONSTRAINTS[label]
        num_tiles = spec.get("num_tiles", tiles)
        if "width" in spec:
            width = spec["width"]
            if tiles % width:
                raise ValueError(f"{label}: tiles={tiles} not divisible by width={width}")
            height = tiles // width
            comment = f"# {label}: {width}x{height} tiles ({tiles} total)"
        else:
            comment = f"# {label}: fixed {num_tiles} tiles"
        if tiles != num_tiles:
            raise ValueError(
                f"{label}: ROM tiles={tiles} != specified num_tiles={num_tiles}"
            )
        args = f"-num_tiles {num_tiles}"
        lines.append(comment)
        lines.append(f"{path_4bpp}: {png_path}")
        lines.append(f"\t$(GBAGFX) $< $@ {args}")
        lines.append("")
    RULES_MK.write_text("\n".join(lines))


def main() -> int:
    label_offsets = read_label_offsets()
    label_to_path = build_label_to_path()
    missing = [label for label in CONSTRAINTS if label not in label_offsets]
    if missing:
        raise KeyError(f"Labels missing from offsets table: {missing}")
    tile_counts = compute_tile_counts(label_offsets)
    emit_rules(label_to_path, tile_counts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
